### ISSUE TITLE
Fix project explorer view of imported projects

### ISSUE THREAD

**Issue by yyalkovich** [krjakbrjak/intellij_bazel_plugin#5]
Currently after importing the project, in the project explorer all packages start from java folder of {packageName}/src/main/.
Much more useful will be to have as starting point folder with the package Name.
![image](https://user-images.githubusercontent.com/77384861/105027664-52ebca00-5a50-11eb-827e-b76cf024d568.png)

**Comment by yyalkovich** [comment]
As side effect in project explorer no resources folders

**Comment by krjakbrjak** [comment]
The path to the source root defines the node name in the project tree view. It seems that there is no simple way to change that, unless the way ContentRootData gets processed is changed.
